### ISSUE TITLE
You don't need to compile GHDL on Travis-Ci by your own.

### ISSUE THREAD

**Issue by Paebbels** [LarsAsplund/synchronization#5]
Hello Lars,

you don't need to compile GHDL from sources on every run.
Have a look at PoC's `/tools/Travis-CI/` directory: https://github.com/VLSI-EDA/PoC/tree/master/tools/Travis-CI

I convinced Tristan to provide "monthly" GHDL builds at GitHub Releases, so when Tristan tags a GHDl version, Travis-CI builds GHDL and a archiv is uploaded to GitHub Releases. This version is then downloaded into PoC's Travis-CI run. => https://github.com/tgingold/ghdl/releases/tag/2016-06-07

``` yml
language: python
matrix:
  include:
    - env: CONFIG="Trusty,Python3.5,libgnat-4.8,grc-1.9"
      os: linux
      sudo: required
      dist: trusty
      python: "3.5"
      before_install:
        - sudo apt-get install -y libgnat-4.8
        - sudo ./tools/Travis-CI/grc.setup.sh
    - env: CONFIG="Precise,Python3.5,gnat-5"
      os: linux
      python: "3.5"
      addons:
        apt:
          packages:
            - gnat-5
  allow_failures:
    - env: CONFIG="Precise,Python3.5,gnat-5"
install:
  - pip3 install -r tools/Travis-CI/requirements.txt
before_script:
  - ./tools/Travis-CI/ghdl.setup.sh
  - ./tools/Travis-CI/poc.setup.sh
script:
  - ./tools/Travis-CI/poc.run.sh "PoC.*"
```

In `ghdl.setup.sh` GHDL gets extracted and installed. Afterwards we copy a set of predefined config files into PoC, so PoC is configured on Travis and can start it's testbenches.

Kind regards
    Patrick
